devgianlu/go-librespot

cmd/daemon/player.go

Fix an oversight in the original alsa mixer implementation.

fix: don't update initial volume when a mixer is configured.

---

cmd/daemon/player.go

1st fix: On the recommended section below a playlist owned by the user, skipping to any song played the first song only.
2nd fix: While skipping in the queue, it only ever skips one song forward.

fix skipping to the wrong song

---

ap/ap.go
cmd/daemon/player.go
dealer/dealer.go
session/session.go

fix: delegate starting receiver loops to caller

---

cmd/daemon/player.go

fix: (skipping) ignore track index when track uri or track uid is available

---

cmd/daemon/player.go

The web player (open.spotify.com) apparently sends this particular format, with `Relative` unset and the index set in `Value`.

fix: support seek_to from the web player

---

ap/ap.go

I sometimes get "connection refused" for no apparent reason, even though the same AP works at other times. So when that happens, try again with a different AP.
I don't know why this happens, but with this patch the connecting code is a bit more robust. I've verified that it works: it connects to the next in the list which usually works.

fix: try multiple times to connect to an AP

---

cmd/daemon/main.go

Instead of failing altogether, this PR falls back to a default configuration file if `-config_path` is not set.
The default configuration file would be the equivalent of:
```yaml
device_name: go-librespot <hostname>
credentials:
type: zeroconf
```

Default configuration file

---

ap/ap.go
dealer/dealer.go

These race conditions may seem harmless, and maybe they are unlikely to cause real trouble, but:
1. There is a theoretical chance they do. A partially written time value in one goroutine may result in an invalid (and very wrong) time in another, leading to misbehaving code.
2. They introduce noise, and make it more difficult to find&fix other race conditions.

fix: avoid race conditions

---

ap/ap.go

* Immediately cancel the context after establishing a connection. It is only used while connecting, so can be cancelled at that point.
* Fix error message when all 6 attempts have failed.
* Use log.WithError to log an error.
See #87

fix: small fixes to accesspoint connect retry logic

---

README.md

Thanks for this daemon!
To make setup a bit easier, I listed the extra dependencies that I had to install. There might be more, but these were the ones I had to install on a Raspberry Pi OS install.

chore: list dependencies in README

---

output/driver_unix.go

Audio is perceived by humans in a logarithmic way. For a good explanation, see:
https://www.dr-lex.be/info-stuff/volumecontrols.html#about
This PR fixes the volume slider to be logarithmic.
OS volume controls (PulseAudio etc) do something similar, for the same reason.

fix: map audio logarithmically, not linearly

---

api-spec.yml
cmd/daemon/api_server.go
cmd/daemon/controls.go
cmd/daemon/player.go

This PR adds a play/pause command, and relative volume changes to the API. I plan to use these in Home Assistant through the [RESTful Command](https://www.home-assistant.io/integrations/rest_command/) integration.
Sadly Home Assistant doesn't support custom players yet in which case we could support whatever protocol it uses in go-librespot, so I'll just use REST commands as a poor man's media player in Home Assistant.

api: allow changing (not just setting) states

---

spclient/spclient.go

I was getting 500 status with empty body randomly throughout the day when PutConnectState was called.
Have tested for a day or so and I am not getting EOF errors anymore.
Commit does:
Retrying the request (not sure how important that method is for the app to run properly) and checking ContentLength so we are not getting EOF errors during decoding JSON.

fix: retry PutConnectState on error, check ContentLength to avoid EOF error

---

cmd/daemon/controls.go
cmd/daemon/player.go
cmd/daemon/state.go

The PlaybackSpeed field must be set to 0 when paused. Otherwise Spotify Android will correctly show the stream as paused but will still move the playback position when redrawing the UI (and for a very short time when resuming playback).
Fixes #104

fix: update PlaybackSpeed when changing the IsPaused flag

---

cmd/daemon/controls.go

This should be implemented some day, but until it is this at least keeps the player from crashing.
This is a more conservative alternative to https://github.com/devgianlu/go-librespot/pull/98.

fix: do not panic when the URI of the next track is unset

---

README.md
cmd/daemon/main.go
config_schema.json

The previous default was to bind to 0.0.0.0 and allow connections from anywhere. I think this is an insecure default, the default should be restricted.
To restore the previous behavior, use:
```yaml
server:
address: ""
```
For example, I'm using the API from Home Assistant running on the same Raspberry Pi. There is no reason for the API to be exposed on my local network. And generally it's a good idea to have safe default values (and require users to opt-in to less safe options).
(Not sure whether this counts as a fix or a feature, but I guess it fixes potential unsafe configurations, so...)

fix: default API to localhost

---

tracks/tracks.go

These tracks aren't directly visible, but they are visible (for a short bit) when pressing the 'prev' button.
Previously this would always show the first track in an album, which is incorrect. This fix makes sure that 'prev' actually shows the previous track.
Perhaps `slices.Reverse` is not the right way to do this, please let me know if there's a better way.

fix: put previous tracks in the right order

---

cmd/daemon/controls.go
cmd/daemon/player.go
dealer/recv.go

The API has an extra parameter `allow_seeking` that indicates whether the seek left is due to pressing the "prev" button, or because the album is swiped right to go to the previous track immediately.
This patch adds support for this feature.
There's still one issue however: when going to the previous song, the player will for a short time show the first track in an album. ~Not sure why, I suspect go-librespot doesn't send the whole queue (so the player doesn't know there are other tracks in the album).~ see https://github.com/devgianlu/go-librespot/pull/113 for a fix to this bug.

fix: don't seek to the start when swiping right

---

cmd/daemon/controls.go
cmd/daemon/player.go
cmd/daemon/state.go

This fixes https://github.com/devgianlu/go-librespot/issues/73 and might help with https://github.com/devgianlu/go-librespot/issues/54.

fix: assign UIDs to newly added tracks

---

audio/decryptor.go

The decryptor was using up a lot of time. For a ~10min song it took about twice the time that it took to run the Vorbis decoder and this time would only go up considering the exponential nature of the loop.
But actually, all it did was count up a number. This can be done using a simple addition instead of a complicated loop. Hence this patch changes the loop to a simple addition.
~It is 32-bits at the moment, which means it would overflow with a stream that's ~64GB~ 48GB big. This is entirely fixable if needed, but 48GB seems like an unlikely large stream.~ Updated to be 64 bits to make me feel better, this is extremely unlikely to ever overflow.
This replaces #120.

feat: improve efficiency of the decryptor

---

player/player.go

This seek takes around 0.5-1ms (when seeking to position 0) on a Raspberry Pi 3 which isn't much, but it's totally unnecessary in most cases so can be skipped.
This is basically the same as #116 but now as a very small performance improvement.

feat: don't seek when it's not needed

---

output/driver_unix.go

This PR fixes two main issues:
* On some hardware, the output stutters a bit. This was the case on my laptop (Fedora Asahi) which despite being very fast still couldn't play audio without crackling on the laptop speakers (it did work over USB though). This was fixed by setting the period size to bufferSize/4, which was previously set to a default (very short) duration.  
I suspect this is the root cause of https://community.volumio.com/t/new-2023-spotify-plugin/63381/354
* When pausing and resuming (possibly with a seek in between), some audio from before the pause would be repeated. This wasn't very noticeable with the previous short period size (80ms or 160ms or so), but with the new period size it suddenly became 2 seconds and _very_ noticeable.  
An easy way to test this bug is to …

Rewrite ALSA buffering

---

output/driver-alsa.go

Previously the output would always be closed, even when calling Pause(). This worked for the most part, somehow, but not with recent changes.
Instead, only close the output when actually getting an ALSA error that can't be recovered from.
---
Did some quick testing and this seems to fix #135. Pause/resume seems to work, and autoplay seems to work as well.

fix: don't close ALSA output when pausing or on EOF

---

cmd/daemon/controls.go
cmd/daemon/player.go

Relative volume changes would use old values, not the new value set by a volume change in the last second. To fix this, update the player state immediately and only delay sending the update (instead of also delaying the update to the player state).
This could mean that another change (such as play/pause) would send an earlier volume update, but I don't think that's a problem. We'll send a PutStateReason_VOLUME_CHANGED anyway after a second.
Fixes https://github.com/devgianlu/go-librespot/issues/141
This is an alternative to #142

fix: fix fast relative volume updates

---

cmd/daemon/player.go

Fixes #140 
For the record, when using `play=true`, the transfer playback command includes the following options:
```json
"options": {
"restore_paused": "resume",
"restore_position": "last_known"
}
``` 
When using `play=false` 
```json
"options": {
"restore_paused": "pause",
"restore_position": "extrapolate"
}
```

web-api: Use Options.RestorePaused when transfering playback

---

version.go

The Go toolchain stores the git commit hash in the binary, which can then be extracted using `debug.ReadBuildInfo`. The advantage is that the commit hash is present even on development builds (`go build` etc), and it simplifies CI _slightly_.

feat: extract commit hash from build info

---

cmd/daemon/main.go
config_schema.json
player/player.go

librespot (Rust) has an option for it, the original client uses album gain automatically if playing from album.
No volume jumps between tracks when playing a live album.

Add config option to use album gain instead of track gain

---

dealer/dealer.go

On error on backoff retry an error message is logged and the mutex unlocked. It is unlocked again outside the error handling and the loop is not stopped (if the unlock wouldn't panic). Fix this by correctly terminating the loop / cleaning up.
Fixes this:
librespot-go-1  | time="2025-04-21T05:15:11Z" level=error msg="failed reconnecting dealer" error="failed obtaining dealer access token: failed renewing login5 access token: failed authenticating with login5: UNKNOWN_ERROR"
librespot-go-1  | fatal error: sync: Unlock of unlocked RWMutex
librespot-go-1  | 
librespot-go-1  | goroutine 20295860 [running]:
librespot-go-1  | sync.fatal({0xb0da65?, 0x2e28ae00000003?})
librespot-go-1  |       /usr/lib/go/src/runtime/panic.go:1007 +0x20
librespot-go-1  | sync.(*RWMutex).Unlock(0x40002be858) …

bugfix: fix double unlock of mutex in dealer recvloop

---

API.md

I noticed a missing field in the docs today when some of my go-librespot websocket parsing code was failing to handle a playing websocket event. I hope this helps!

chore: add missing websocket field

---

CROSS_COMPILE.md
Dockerfile.build

Was crosscompiling go-librespot and noticed that it was very slow compiling ALSA. This fixes that by making it use all available cores. Also noticed a typo in the arm64 crosscompile documentation which caused a failure running the go compile command in docker.
Not sure where the linebreak fixes at the end of the files come from.... Never had that on other projects. I'll try to check if it's somehow not using `\n`

Docker: multithreaded dependency build
